export interface IPlayer {
  assists_per_game: number,
  blocks_per_game: number,
  defensive_rebounds_per_game: number,
  field_goal_percentage: number,
  field_goals_attempted_per_game: number,
  field_goals_made_per_game: number,
  free_throw_percentage: number,
  games_played: number,
  minutes_per_game: number,
  name: string,
  offensive_rebounds_per_game: number,
  player_efficiency_rating: number,
  points_per_game: number,
  rebounds_per_game: number,
  steals_per_game: number,
  team_acronym: string,
  team_name: string,
  three_point_attempted_per_game: number,
  three_point_made_per_game: number,
  three_point_percentage: number,
  turnovers_per_game: number,
  is_liked: boolean;
}
